/**
 * AI JOKER-C2 EVT Memory Ledger
 *
 * Append-only JSONL ledger for semantic EVT/IPR-bound memory events.
 *
 * This module persists EvtMemoryEvent records generated by lib/evt-memory.ts.
 * It does not replace the governed runtime EVT ledger in lib/evt-ledger.ts.
 *
 * Separation:
 * - evt-ledger.ts stores governed RuntimeEvent records.
 * - evt-memory-ledger.ts stores semantic continuity records.
 *
 * Prototype note:
 * This local file adapter is suitable for local development and controlled
 * prototype use. Serverless production deployments should use persistent
 * external storage such as Postgres, KV, object storage, or another managed
 * append-only store.
 */

import { appendFile, mkdir, readFile, stat, writeFile } from "fs/promises";
import path from "path";

import {
  sha256Short,
  type DocumentFamily,
  type EvtMemoryEvent,
  type MemorySource,
  type RuntimeDecision,
  type RuntimeState,
  type SemanticState
} from "./evt-memory";

export const DEFAULT_EVT_MEMORY_LEDGER_DIR = path.join(
  process.cwd(),
  "ledger"
);

export const DEFAULT_EVT_MEMORY_LEDGER_FILE =
  process.env.JOKER_EVT_MEMORY_LEDGER_FILE ||
  path.join(DEFAULT_EVT_MEMORY_LEDGER_DIR, "evt-memory.jsonl");

export type EvtMemoryLedgerAppendStatus =
  | "APPENDED"
  | "REJECTED"
  | "FAILED";

export type EvtMemoryLedgerReadStatus =
  | "READY"
  | "EMPTY"
  | "MISSING"
  | "FAILED";

export type EvtMemoryLedgerVerificationStatus =
  | "VERIFIABLE"
  | "PARTIAL"
  | "INVALID"
  | "UNVERIFIED";

export type EvtMemoryLedgerAppendResult = {
  status: EvtMemoryLedgerAppendStatus;
  evt?: string;
  prev?: string;
  ledgerPath: string;
  reason: string;
};

export type EvtMemoryLedgerReadResult = {
  status: EvtMemoryLedgerReadStatus;
  ledgerPath: string;
  events: EvtMemoryEvent[];
  invalidLines: number;
  reason: string;
};

export type EvtMemoryLedgerLookupResult = {
  found: boolean;
  event?: EvtMemoryEvent;
  ledgerPath: string;
  reason: string;
};

export type EvtMemoryLedgerSummary = {
  ledgerPath: string;
  totalEvents: number;
  lastEvent: string;
  lastTraceHash: string;
  invalidLines: number;
  verificationStatus: EvtMemoryLedgerVerificationStatus;
};

export type EvtMemoryLedgerIntegrityResult = {
  status: EvtMemoryLedgerVerificationStatus;
  ledgerPath: string;
  totalEvents: number;
  invalidLines: number;
  hashValid: boolean;
  chainContinuity: "LINEAR" | "PARTIAL" | "UNVERIFIED";
  warnings: string[];
};

export type EvtMemoryLedgerPublicEvent = {
  evt: string;
  prev: string;
  t: string;
  entity: string;
  ipr: string;
  sessionId: string;
  state: RuntimeState;
  decision: RuntimeDecision;
  documentFamily: DocumentFamily;
  activeDocument: string | null;
  semanticTags: string[];
  userIntent: string;
  governedEvt: string | null;
  governedHash: string | null;
  traceHash: string;
};

export type LedgerMemoryContext = {
  used: boolean;
  source: "LEDGER_SESSION" | "LEDGER_IPR_CANONICAL" | "LEDGER_IPR_RECENT" | "NONE";
  text: string;
  semanticState: SemanticState | null;
  lastEventId: string | null;
};

const EVENT_KIND = "IPR_BOUND_CHAT_MEMORY" as const;
const CANONICAL_SESSION_ID = "CANONICAL";
const MAX_CONTEXT_EVENTS = 10;
const MAX_CONTEXT_TEXT_CHARS = 12000;

export async function ensureEvtMemoryLedger(
  ledgerPath = DEFAULT_EVT_MEMORY_LEDGER_FILE
): Promise<void> {
  const directory = path.dirname(ledgerPath);

  await mkdir(directory, { recursive: true });

  try {
    await stat(ledgerPath);
  } catch {
    await writeFile(ledgerPath, "", "utf8");
  }
}

export async function appendEvtMemoryEvent(
  event: EvtMemoryEvent,
  ledgerPath = DEFAULT_EVT_MEMORY_LEDGER_FILE
): Promise<EvtMemoryLedgerAppendResult> {
  try {
    await ensureEvtMemoryLedger(ledgerPath);

    if (!isEvtMemoryEventStructurallyValid(event)) {
      return {
        status: "REJECTED",
        evt: event.evt,
        prev: event.prev,
        ledgerPath,
        reason:
          "EVT memory event is structurally invalid and was not appended."
      };
    }

    if (!isEvtMemoryEventHashValid(event)) {
      return {
        status: "REJECTED",
        evt: event.evt,
        prev: event.prev,
        ledgerPath,
        reason: "EVT memory event hash is invalid and was not appended."
      };
    }

    await appendFile(ledgerPath, `${buildEvtMemoryEventLine(event)}\n`, "utf8");

    return {
      status: "APPENDED",
      evt: event.evt,
      prev: event.prev,
      ledgerPath,
      reason: "EVT memory event appended to memory ledger."
    };
  } catch (error) {
    return {
      status: "FAILED",
      evt: event.evt,
      prev: event.prev,
      ledgerPath,
      reason:
        error instanceof Error
          ? error.message
          : "Unknown EVT memory ledger append failure."
    };
  }
}

export async function appendEvtMemoryEvents(
  events: EvtMemoryEvent[],
  ledgerPath = DEFAULT_EVT_MEMORY_LEDGER_FILE
): Promise<EvtMemoryLedgerAppendResult[]> {
  const results: EvtMemoryLedgerAppendResult[] = [];

  for (const event of events) {
    results.push(await appendEvtMemoryEvent(event, ledgerPath));
  }

  return results;
}

export async function readEvtMemoryLedger(
  ledgerPath = DEFAULT_EVT_MEMORY_LEDGER_FILE
): Promise<EvtMemoryLedgerReadResult> {
  try {
    await ensureEvtMemoryLedger(ledgerPath);

    const raw = await readFile(ledgerPath, "utf8");

    if (!raw.trim()) {
      return {
        status: "EMPTY",
        ledgerPath,
        events: [],
        invalidLines: 0,
        reason: "EVT memory ledger exists but contains no events."
      };
    }

    const lines = raw
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean);

    const events: EvtMemoryEvent[] = [];
    let invalidLines = 0;

    for (const line of lines) {
      const event = parseEvtMemoryEventLine(line);

      if (!event) {
        invalidLines += 1;
        continue;
      }

      events.push(event);
    }

    return {
      status: events.length > 0 ? "READY" : "EMPTY",
      ledgerPath,
      events,
      invalidLines,
      reason:
        invalidLines > 0
          ? "EVT memory ledger read completed with invalid lines."
          : "EVT memory ledger read completed."
    };
  } catch (error) {
    return {
      status: "FAILED",
      ledgerPath,
      events: [],
      invalidLines: 0,
      reason:
        error instanceof Error
          ? error.message
          : "Unknown EVT memory ledger read failure."
    };
  }
}

export async function readEvtMemoryEvents(
  limit?: number,
  ledgerPath = DEFAULT_EVT_MEMORY_LEDGER_FILE
): Promise<EvtMemoryEvent[]> {
  const result = await readEvtMemoryLedger(ledgerPath);

  if (typeof limit === "number" && limit > 0) {
    return result.events.slice(-limit);
  }

  return result.events;
}

export async function findEvtMemoryEventById(
  evt: string,
  ledgerPath = DEFAULT_EVT_MEMORY_LEDGER_FILE
): Promise<EvtMemoryLedgerLookupResult> {
  const normalizedEvt = evt.trim();

  if (!normalizedEvt) {
    return {
      found: false,
      ledgerPath,
      reason: "No EVT memory identifier was provided."
    };
  }

  const events = await readEvtMemoryEvents(undefined, ledgerPath);
  const event = events.find((item) => item.evt === normalizedEvt);

  if (!event) {
    return {
      found: false,
      ledgerPath,
      reason: `EVT memory event ${normalizedEvt} was not found.`
    };
  }

  return {
    found: true,
    event,
    ledgerPath,
    reason: `EVT memory event ${normalizedEvt} found.`
  };
}

export async function getEvtMemoryEventById(
  evt: string,
  ledgerPath = DEFAULT_EVT_MEMORY_LEDGER_FILE
): Promise<EvtMemoryEvent | null> {
  const result = await findEvtMemoryEventById(evt, ledgerPath);

  return result.event ?? null;
}

export async function getLastEvtMemoryEvent(input?: {
  ipr?: string;
  sessionId?: string;
  ledgerPath?: string;
}): Promise<EvtMemoryEvent | null> {
  const events = await readEvtMemoryEvents(undefined, input?.ledgerPath);

  const filtered = events.filter((event) => {
    if (input?.ipr && event.ipr !== input.ipr) {
      return false;
    }

    if (input?.sessionId && event.sessionId !== input.sessionId) {
      return false;
    }

    return true;
  });

  return filtered[filtered.length - 1] ?? null;
}

export async function buildEvtMemoryLedgerSummary(
  ledgerPath = DEFAULT_EVT_MEMORY_LEDGER_FILE
): Promise<EvtMemoryLedgerSummary> {
  const readResult = await readEvtMemoryLedger(ledgerPath);
  const lastEvent = readResult.events[readResult.events.length - 1];
  const integrity = await verifyEvtMemoryLedger(ledgerPath);

  return {
    ledgerPath,
    totalEvents: readResult.events.length,
    lastEvent: lastEvent?.evt ?? "GENESIS",
    lastTraceHash: lastEvent?.anchors.traceHash ?? "",
    invalidLines: readResult.invalidLines,
    verificationStatus: integrity.status
  };
}

export async function verifyEvtMemoryLedger(
  ledgerPath = DEFAULT_EVT_MEMORY_LEDGER_FILE
): Promise<EvtMemoryLedgerIntegrityResult> {
  const readResult = await readEvtMemoryLedger(ledgerPath);
  const events = readResult.events;

  const hashValid = events.every((event) => isEvtMemoryEventHashValid(event));
  const chainContinuity = inferChainContinuity(events);

  const warnings = buildWarnings({
    totalEvents: events.length,
    invalidLines: readResult.invalidLines,
    hashValid,
    chainContinuity
  });

  return {
    status: inferVerificationStatus({
      totalEvents: events.length,
      invalidLines: readResult.invalidLines,
      hashValid,
      chainContinuity
    }),
    ledgerPath,
    totalEvents: events.length,
    invalidLines: readResult.invalidLines,
    hashValid,
    chainContinuity,
    warnings
  };
}

export async function exportPublicEvtMemoryLedgerView(
  limit?: number,
  ledgerPath = DEFAULT_EVT_MEMORY_LEDGER_FILE
): Promise<EvtMemoryLedgerPublicEvent[]> {
  const events = await readEvtMemoryEvents(limit, ledgerPath);

  return events.map((event) => toPublicEvtMemoryEvent(event));
}

export async function clearEvtMemoryLedgerForLocalDevelopmentOnly(
  ledgerPath = DEFAULT_EVT_MEMORY_LEDGER_FILE
): Promise<void> {
  await ensureEvtMemoryLedger(ledgerPath);
  await writeFile(ledgerPath, "", "utf8");
}

export async function buildEvtMemoryContextFromLedger(input: {
  sessionId: string;
  ipr: string;
  message: string;
  ledgerPath?: string;
}): Promise<LedgerMemoryContext> {
  const readResult = await readEvtMemoryLedger(input.ledgerPath);

  if (readResult.events.length === 0) {
    return {
      used: false,
      source: "NONE",
      text: "Nessuna memoria EVT/IPR-bound disponibile nel ledger semantico.",
      semanticState: null,
      lastEventId: null
    };
  }

  const sessionEvents = readResult.events.filter(
    (event) => event.ipr === input.ipr && event.sessionId === input.sessionId
  );

  if (sessionEvents.length > 0) {
    const semanticState = buildSemanticStateFromEvents({
      ipr: input.ipr,
      sessionId: input.sessionId,
      events: sessionEvents
    });

    return {
      used: true,
      source: "LEDGER_SESSION",
      text: buildLedgerMemoryText({
        source: "LEDGER_SESSION",
        semanticState,
        events: sessionEvents
      }),
      semanticState,
      lastEventId: semanticState.lastEventId
    };
  }

  const canonicalEvents = readResult.events.filter(
    (event) => event.ipr === input.ipr && event.sessionId === CANONICAL_SESSION_ID
  );

  if (canonicalEvents.length > 0) {
    const semanticState = buildSemanticStateFromEvents({
      ipr: input.ipr,
      sessionId: CANONICAL_SESSION_ID,
      events: canonicalEvents
    });

    return {
      used: true,
      source: "LEDGER_IPR_CANONICAL",
      text: buildLedgerMemoryText({
        source: "LEDGER_IPR_CANONICAL",
        semanticState,
        events: canonicalEvents
      }),
      semanticState,
      lastEventId: semanticState.lastEventId
    };
  }

  const recentEvents = selectRelevantRecentEvents({
    events: readResult.events.filter((event) => event.ipr === input.ipr),
    message: input.message
  });

  if (recentEvents.length > 0) {
    const sessionId = recentEvents[recentEvents.length - 1]?.sessionId || input.sessionId;

    const semanticState = buildSemanticStateFromEvents({
      ipr: input.ipr,
      sessionId,
      events: recentEvents
    });

    return {
      used: true,
      source: "LEDGER_IPR_RECENT",
      text: buildLedgerMemoryText({
        source: "LEDGER_IPR_RECENT",
        semanticState,
        events: recentEvents
      }),
      semanticState,
      lastEventId: semanticState.lastEventId
    };
  }

  return {
    used: false,
    source: "NONE",
    text: "Nessuna memoria EVT/IPR-bound rilevante disponibile nel ledger semantico.",
    semanticState: null,
    lastEventId: null
  };
}

export function buildEvtMemoryTracePayload(event: EvtMemoryEvent) {
  return {
    evt: event.evt,
    prev: event.prev,
    t: event.t,
    entity: event.entity,
    ipr: event.ipr,
    sessionId: event.sessionId,
    kind: event.kind,
    state: event.state,
    decision: event.decision,
    contextClass: event.contextClass,
    documentMode: event.documentMode,
    documentFamily: event.documentFamily,
    activeDocument: event.activeDocument,
    semanticTags: event.semanticTags,
    userIntent: event.userIntent,
    memoryDelta: event.memoryDelta,
    nextContext: event.nextContext,
    governedEvt: event.governedEvt,
    governedHash: event.governedHash,
    inputHash: event.anchors.inputHash,
    outputHash: event.anchors.outputHash
  };
}

export function rebuildEvtMemoryEventHash(event: EvtMemoryEvent): string {
  return sha256Short(buildEvtMemoryTracePayload(event));
}

export function isEvtMemoryEventHashValid(event: EvtMemoryEvent): boolean {
  return rebuildEvtMemoryEventHash(event) === event.anchors.traceHash;
}

export function isEvtMemoryEventStructurallyValid(
  event: Partial<EvtMemoryEvent>
): event is EvtMemoryEvent {
  return Boolean(
    event.evt &&
      event.prev &&
      event.t &&
      event.entity &&
      event.ipr &&
      event.sessionId &&
      event.kind === EVENT_KIND &&
      event.state &&
      event.decision &&
      event.contextClass &&
      event.documentMode &&
      event.documentFamily &&
      Array.isArray(event.semanticTags) &&
      typeof event.userIntent === "string" &&
      typeof event.memoryDelta === "string" &&
      typeof event.nextContext === "string" &&
      event.anchors?.inputHash &&
      event.anchors?.outputHash &&
      event.anchors?.traceHash
  );
}

export function getEvtMemoryEventMissingFields(
  event: Partial<EvtMemoryEvent>
): string[] {
  const missing: string[] = [];

  if (!event.evt) missing.push("evt");
  if (!event.prev) missing.push("prev");
  if (!event.t) missing.push("t");
  if (!event.entity) missing.push("entity");
  if (!event.ipr) missing.push("ipr");
  if (!event.sessionId) missing.push("sessionId");
  if (event.kind !== EVENT_KIND) missing.push("kind");
  if (!event.state) missing.push("state");
  if (!event.decision) missing.push("decision");
  if (!event.contextClass) missing.push("contextClass");
  if (!event.documentMode) missing.push("documentMode");
  if (!event.documentFamily) missing.push("documentFamily");
  if (!Array.isArray(event.semanticTags)) missing.push("semanticTags");
  if (typeof event.userIntent !== "string") missing.push("userIntent");
  if (typeof event.memoryDelta !== "string") missing.push("memoryDelta");
  if (typeof event.nextContext !== "string") missing.push("nextContext");
  if (!event.anchors?.inputHash) missing.push("anchors.inputHash");
  if (!event.anchors?.outputHash) missing.push("anchors.outputHash");
  if (!event.anchors?.traceHash) missing.push("anchors.traceHash");

  return missing;
}

export function buildEvtMemoryEventLine(event: EvtMemoryEvent): string {
  return JSON.stringify(event);
}

export function parseEvtMemoryEventLine(line: string): EvtMemoryEvent | null {
  try {
    const parsed = JSON.parse(line) as EvtMemoryEvent;

    if (!isEvtMemoryEventStructurallyValid(parsed)) {
      return null;
    }

    if (!isEvtMemoryEventHashValid(parsed)) {
      return null;
    }

    return parsed;
  } catch {
    return null;
  }
}

export function toPublicEvtMemoryEvent(
  event: EvtMemoryEvent
): EvtMemoryLedgerPublicEvent {
  return {
    evt: event.evt,
    prev: event.prev,
    t: event.t,
    entity: event.entity,
    ipr: event.ipr,
    sessionId: event.sessionId,
    state: event.state,
    decision: event.decision,
    documentFamily: event.documentFamily,
    activeDocument: event.activeDocument,
    semanticTags: event.semanticTags,
    userIntent: event.userIntent,
    governedEvt: event.governedEvt,
    governedHash: event.governedHash,
    traceHash: event.anchors.traceHash
  };
}

export function buildSemanticStateFromEvents(input: {
  ipr: string;
  sessionId: string;
  events: EvtMemoryEvent[];
}): SemanticState {
  const ordered = [...input.events].sort((a, b) => {
    return Date.parse(a.t) - Date.parse(b.t);
  });

  const lastEvent = ordered[ordered.length - 1] ?? null;
  const activeDocument = getLastNonEmpty(
    ordered.map((event) => event.activeDocument)
  );

  const documentFamily =
    getLastNonGeneralDocumentFamily(ordered.map((event) => event.documentFamily)) ||
    "GENERAL_DOCUMENT";

  const centralThesis = extractCentralThesisFromEvents(ordered);

  const semanticTags = mergeUnique(
    ordered.flatMap((event) => event.semanticTags),
    64
  );

  const referenceRules = buildReferenceRulesFromEvents(ordered);

  const accumulatedMeaning = ordered
    .map((event) => event.memoryDelta)
    .filter(Boolean)
    .join(" ")
    .slice(-4500);

  return {
    ipr: input.ipr,
    sessionId: input.sessionId,
    activeDocument,
    documentFamily,
    centralThesis,
    semanticTags,
    referenceRules,
    accumulatedMeaning,
    lastEventId: lastEvent?.evt ?? null,
    lastGovernedEvt: getLastNonEmpty(ordered.map((event) => event.governedEvt)),
    lastGovernedHash: getLastNonEmpty(
      ordered.map((event) => event.governedHash)
    ),
    updatedAt: lastEvent?.t ?? new Date().toISOString()
  };
}

function buildLedgerMemoryText(input: {
  source: LedgerMemoryContext["source"];
  semanticState: SemanticState;
  events: EvtMemoryEvent[];
}): string {
  const recentEvents = input.events.slice(-MAX_CONTEXT_EVENTS);

  return [
    "MEMORIA EVT/IPR-BOUND RICOSTRUITA DA LEDGER:",
    `MEMORY_SOURCE: ${input.source}`,
    `IPR: ${input.semanticState.ipr}`,
    `SESSION_ID: ${input.semanticState.sessionId}`,
    `ACTIVE_DOCUMENT: ${input.semanticState.activeDocument || "none"}`,
    `DOCUMENT_FAMILY: ${input.semanticState.documentFamily}`,
    `CENTRAL_THESIS: ${input.semanticState.centralThesis || "none"}`,
    `LAST_MEMORY_EVT: ${input.semanticState.lastEventId || "none"}`,
    `LAST_GOVERNED_EVT: ${input.semanticState.lastGovernedEvt || "none"}`,
    `LAST_GOVERNED_HASH: ${input.semanticState.lastGovernedHash || "none"}`,
    `SEMANTIC_TAGS: ${
      input.semanticState.semanticTags.length > 0
        ? input.semanticState.semanticTags.join(", ")
        : "none"
    }`,
    "",
    "REFERENCE_RULES:",
    input.semanticState.referenceRules.length > 0
      ? input.semanticState.referenceRules.join("\n")
      : "none",
    "",
    "ACCUMULATED_MEANING:",
    input.semanticState.accumulatedMeaning || "none",
    "",
    "RECENT_EVT_MEMORY_LEDGER:",
    ...recentEvents.map((event) =>
      [
        `- ${event.evt}`,
        `  prev: ${event.prev}`,
        `  governedEvt: ${event.governedEvt || "none"}`,
        `  governedHash: ${event.governedHash || "none"}`,
        `  family: ${event.documentFamily}`,
        `  activeDocument: ${event.activeDocument || "none"}`,
        `  intent: ${event.userIntent}`,
        `  delta: ${event.memoryDelta}`,
        `  nextContext: ${event.nextContext}`,
        `  traceHash: ${event.anchors.traceHash}`
      ].join("\n")
    ),
    "",
    "ISTRUZIONE DI RECUPERO:",
    "Questa memoria è stata ricostruita dal ledger semantico. Usala come continuità IPR-bound quando la memoria volatile di sessione non è disponibile."
  ]
    .join("\n")
    .slice(0, MAX_CONTEXT_TEXT_CHARS);
}

function selectRelevantRecentEvents(input: {
  events: EvtMemoryEvent[];
  message: string;
}): EvtMemoryEvent[] {
  const scored = input.events
    .map((event) => ({
      event,
      score: scoreEventForMessage(event, input.message),
      timestamp: Date.parse(event.t) || 0
    }))
    .filter((item) => item.score > 0)
    .sort((a, b) => {
      if (b.score !== a.score) {
        return b.score - a.score;
      }

      return b.timestamp - a.timestamp;
    });

  if (scored.length === 0) {
    return input.events.slice(-MAX_CONTEXT_EVENTS);
  }

  return scored
    .slice(0, MAX_CONTEXT_EVENTS)
    .map((item) => item.event)
    .sort((a, b) => Date.parse(a.t) - Date.parse(b.t));
}

function scoreEventForMessage(event: EvtMemoryEvent, message: string): number {
  const normalizedMessage = normalizeForMatch(message);
  const messageTags = detectTags(message);

  let score = 0;

  for (const tag of messageTags) {
    if (event.semanticTags.includes(tag)) {
      score += 10;
    }
  }

  if (
    event.activeDocument &&
    normalizedMessage.includes(normalizeForMatch(event.activeDocument))
  ) {
    score += 15;
  }

  if (
    event.documentFamily !== "GENERAL_DOCUMENT" &&
    normalizedMessage.includes(normalizeForMatch(event.documentFamily))
  ) {
    score += 8;
  }

  if (event.documentFamily === "HBCE_RUNTIME") {
    const runtimeTerms = [
      "joker",
      "joker-c2",
      "ipr",
      "evt",
      "memoria",
      "ledger",
      "runtime",
      "route",
      "fail closed",
      "fail-closed",
      "programmazione",
      "ripara",
      "danno"
    ];

    if (runtimeTerms.some((term) => normalizedMessage.includes(term))) {
      score += 20;
    }
  }

  const updatedAt = Date.parse(event.t);

  if (Number.isFinite(updatedAt)) {
    const hours = Math.max(1, (Date.now() - updatedAt) / (1000 * 60 * 60));
    score += Math.max(0, 10 - Math.floor(hours / 12));
  }

  return score;
}

function detectTags(text: string): string[] {
  const lower = text.toLowerCase();

  const dictionary = [
    "apokalypsis",
    "apocalipsis",
    "apocalisse",
    "decadimento",
    "crollo",
    "esposizione",
    "sistema culturale",
    "sistema politico",
    "sistema sociale",
    "popolo",
    "05-04-2026",
    "decisione",
    "costo",
    "traccia",
    "tempo",
    "matrix",
    "hbce",
    "joker-c2",
    "ai joker-c2",
    "ipr",
    "identity primary record",
    "trac",
    "evt",
    "evt chain",
    "ledger",
    "runtime",
    "fail-closed",
    "governance",
    "continuità",
    "continuita",
    "verifica",
    "auditabilità",
    "auditabilita",
    "esoterologia",
    "corpus",
    "lex hermeticum",
    "alien code",
    "anticristo",
    "biocybersecurity",
    "biocibersicurezza",
    "biocibernetica"
  ];

  return dictionary.filter((item) => lower.includes(item));
}

function normalizeForMatch(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[’']/g, " ")
    .replace(/[^\p{L}\p{N}./_-]+/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function getLastNonEmpty(values: Array<string | null | undefined>): string | null {
  for (let index = values.length - 1; index >= 0; index -= 1) {
    const value = values[index];

    if (typeof value === "string" && value.trim()) {
      return value.trim();
    }
  }

  return null;
}

function getLastNonGeneralDocumentFamily(
  values: DocumentFamily[]
): DocumentFamily | null {
  for (let index = values.length - 1; index >= 0; index -= 1) {
    const value = values[index];

    if (value && value !== "GENERAL_DOCUMENT") {
      return value;
    }
  }

  return null;
}

function extractCentralThesisFromEvents(events: EvtMemoryEvent[]): string | null {
  for (let index = events.length - 1; index >= 0; index -= 1) {
    const event = events[index];
    const match = event?.memoryDelta.match(
      /Tesi centrale incorporata:\s*(.+?)(?:\s+Regola di continuità:|$)/
    );

    if (match?.[1]?.trim()) {
      return match[1].trim();
    }
  }

  return null;
}

function buildReferenceRulesFromEvents(events: EvtMemoryEvent[]): string[] {
  const rules: string[] = [];

  for (const event of events) {
    if (event.activeDocument && event.documentFamily === "APOKALYPSIS") {
      rules.push(
        `"questa opera", "questo testo", "Apokalypsis", "i punti forti" = ${event.activeDocument}`
      );
    }

    if (event.documentFamily === "HBCE_RUNTIME") {
      rules.push(
        `"JOKER-C2", "IPR", "EVT", "memoria", "ledger", "runtime", "fail-closed" = contesto HBCE_RUNTIME attivo`
      );
    }

    if (event.activeDocument) {
      rules.push(`documento attivo = ${event.activeDocument}`);
    }

    if (event.governedEvt) {
      rules.push(`ultimo governed EVT = ${event.governedEvt}`);
    }
  }

  return mergeUnique(rules, 20);
}

function mergeUnique(values: string[], limit = 32): string[] {
  return Array.from(new Set(values.filter(Boolean))).slice(0, limit);
}

function inferChainContinuity(
  events: EvtMemoryEvent[]
): EvtMemoryLedgerIntegrityResult["chainContinuity"] {
  if (events.length === 0) {
    return "UNVERIFIED";
  }

  if (events.length === 1) {
    return "LINEAR";
  }

  let linearLinks = 0;

  for (let index = 1; index < events.length; index += 1) {
    const current = events[index];
    const previous = events[index - 1];

    if (!current || !previous) {
      continue;
    }

    if (current.prev === previous.evt) {
      linearLinks += 1;
    }
  }

  if (linearLinks === events.length - 1) {
    return "LINEAR";
  }

  return "PARTIAL";
}

function inferVerificationStatus(input: {
  totalEvents: number;
  invalidLines: number;
  hashValid: boolean;
  chainContinuity: EvtMemoryLedgerIntegrityResult["chainContinuity"];
}): EvtMemoryLedgerVerificationStatus {
  if (input.totalEvents === 0) {
    return "UNVERIFIED";
  }

  if (input.invalidLines > 0 || !input.hashValid) {
    return "INVALID";
  }

  if (input.chainContinuity === "PARTIAL") {
    return "PARTIAL";
  }

  return "VERIFIABLE";
}

function buildWarnings(input: {
  totalEvents: number;
  invalidLines: number;
  hashValid: boolean;
  chainContinuity: EvtMemoryLedgerIntegrityResult["chainContinuity"];
}): string[] {
  const warnings: string[] = [];

  if (input.totalEvents === 0) {
    warnings.push("EVT memory ledger contains no events.");
  }

  if (input.invalidLines > 0) {
    warnings.push(
      `EVT memory ledger contains ${input.invalidLines} invalid line(s).`
    );
  }

  if (!input.hashValid) {
    warnings.push("One or more EVT memory event hashes are invalid.");
  }

  if (input.chainContinuity === "PARTIAL") {
    warnings.push(
      "EVT memory ledger is partially ordered. This can happen when multiple sessions or canonical IPR memory slots write to the same ledger."
    );
  }

  return Array.from(new Set(warnings));
}
