import { createHash } from "node:crypto";
import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const ROUTE_REVISION = "HBCE-IPR-RUNTIME-API-v1-EVENTS-CONTRACT-v0.1";
const API_VERSION = "v1";
const PRODUCT_NAME = "HBCE IPR Operational Identity & Proof Layer";
const RUNTIME_NAME = "AI_JOKER_C2_SAAS_CORE_v0_1";

const DEFAULT_HUMAN_IPR = "IPR-88505FE91013DCFE97C56ED1";
const DEFAULT_RUNTIME_IPR = "IPR-AI-0001";
const DEFAULT_TENANT = "HBCE-TENANT-SELF-PILOT";
const DEFAULT_WORKSPACE = "HBCE-WORKSPACE-RND";

const LEGAL_CERTIFICATION = false;
const OPC_BOUNDARY = "technical proof receipt only";
const IPR_CARD_BOUNDARY =
  "IPR Card is an internal operational identity certificate, not an official public identity document.";

const EVENT_LEDGER_BOUNDARY =
  "This public v1 route exposes the EVT contract and lookup envelope only. It does not perform database reads or create new runtime events.";

const SUPPORTED_EVENT_TYPES = [
  "IPR_SESSION_OPENED",
  "GOVERNED_CHAT_RESPONSE",
  "OPERATION_ACCEPTED",
  "OPERATION_STATUS_LOOKUP",
  "FILE_INGESTION_RECEIPT",
  "SOURCE_INTELLIGENCE_SUMMARY",
  "OPC_TECHNICAL_PROOF_RECEIPT",
  "AUDIT_LOG_RECORD",
  "MODEL_USAGE_RECORD"
] as const;

type EventQuery = {
  eventId: string | null;
  humanIpr: string;
  runtimeIpr: string;
  tenant: string;
  workspace: string;
  limit: number;
};

function isoNow(): string {
  return new Date().toISOString();
}

function sha256(value: string): string {
  return `sha256:${createHash("sha256").update(value, "utf8").digest("hex")}`;
}

function safeString(value: string | null): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function boundedInteger(value: string | null, fallback: number, min: number, max: number): number {
  if (!value) return fallback;
  const parsed = Number.parseInt(value, 10);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.max(min, Math.min(max, parsed));
}

function normalizeEventQuery(request: NextRequest): EventQuery {
  const params = request.nextUrl.searchParams;

  return {
    eventId: safeString(params.get("eventId")),
    humanIpr: safeString(params.get("humanIpr")) ?? DEFAULT_HUMAN_IPR,
    runtimeIpr: safeString(params.get("runtimeIpr")) ?? DEFAULT_RUNTIME_IPR,
    tenant: safeString(params.get("tenant")) ?? DEFAULT_TENANT,
    workspace: safeString(params.get("workspace")) ?? DEFAULT_WORKSPACE,
    limit: boundedInteger(params.get("limit"), 25, 1, 100)
  };
}

function buildTemporalSeal(generatedAt: string) {
  return {
    status: "DUAL_TIME_SEAL_READY",
    generatedAtUtc: generatedAt,
    locality: "Torino / Italia / Europa · UTC+2",
    runtimeBirth: "2026-01-19T15:30:00+01:00",
    timezone: "Europe/Rome"
  };
}

function buildBoundary() {
  return {
    legalCertification: LEGAL_CERTIFICATION,
    opcBoundary: OPC_BOUNDARY,
    iprCardBoundary: IPR_CARD_BOUNDARY,
    eventLedgerBoundary: EVENT_LEDGER_BOUNDARY,
    rawTextPersistence: false,
    automaticIprMemoryWrite: false,
    sourceProfileSaveMode: "EXPLICIT_OPERATOR_SAVE_ONLY",
    runtimeMemoryWriteSuppressed: true,
    semanticPersistenceSuppressed: true,
    noNewIprMemory: true,
    noNewSemanticMemoryPersistable: true
  };
}

function buildPublicSurface() {
  return {
    currentEndpoint: "GET /api/v1/events",
    publicEquivalent: "GET /v1/events",
    relatedEndpoints: [
      "GET /v1/health",
      "GET /v1/capabilities",
      "POST /v1/ipr/session",
      "POST /v1/chat",
      "POST /v1/operations",
      "GET /v1/operations/{operationId}",
      "GET /v1/events",
      "GET /v1/opc/{opcId}",
      "GET /v1/audit/{auditId}",
      "GET /v1/model-usage/{usageId}"
    ],
    queryParameters: {
      eventId: "Optional EVT identifier. Contract lookup envelope only in this route.",
      humanIpr: "Optional operational subject IPR. Defaults to self-pilot Human IPR.",
      runtimeIpr: "Optional runtime IPR. Defaults to IPR-AI-0001.",
      tenant: "Optional tenant. Defaults to HBCE-TENANT-SELF-PILOT.",
      workspace: "Optional workspace. Defaults to HBCE-WORKSPACE-RND.",
      limit: "Optional bounded integer from 1 to 100. Defaults to 25."
    }
  };
}

function buildEventContract() {
  return {
    status: "EVT_LEDGER_CONTRACT_READY",
    ledger: "EVT",
    purpose:
      "EVT records the technical operational event generated by governed JOKER-C2 runtime activity.",
    eventIdFormat: "EVT-<YYYYMMDDHHMMSS>-<8_HEX> or EVT-V1-<DOMAIN>-<HASH>",
    minimumEventFields: {
      eventId: "string",
      eventType: "string",
      subjectIpr: "string",
      runtimeIpr: "string",
      tenant: "string",
      workspace: "string",
      createdAt: "ISO-8601 UTC timestamp",
      eventHash: "sha256:<hex>",
      legalCertification: false,
      opcBoundary: OPC_BOUNDARY
    },
    supportedEventTypes: SUPPORTED_EVENT_TYPES,
    relationModel: {
      chat: "POST /v1/chat SHOULD return responseEvt and optionally linked opcId/auditId/usageId.",
      operations:
        "POST /v1/operations SHOULD return operationId, responseEvt and optionally opcId.",
      opc: "An OPC receipt MAY reference an EVT identifier as its technical proof target.",
      audit: "An audit record MAY reference EVT, OPC and model usage identifiers.",
      modelUsage: "A usage record MAY reference the response EVT generated by an AI interaction."
    }
  };
}

function buildLookupEnvelope(query: EventQuery, generatedAt: string) {
  const requestHash = sha256(
    JSON.stringify({
      endpoint: "GET /api/v1/events",
      eventId: query.eventId,
      humanIpr: query.humanIpr,
      runtimeIpr: query.runtimeIpr,
      tenant: query.tenant,
      workspace: query.workspace,
      limit: query.limit,
      generatedAt
    })
  );

  return {
    status: query.eventId
      ? "EVT_LOOKUP_NOT_PERSISTED_BY_THIS_ROUTE"
      : "EVT_LEDGER_LIST_NOT_PERSISTED_BY_THIS_ROUTE",
    lookupMode: "CONTRACT_RECEIPT_ONLY",
    persistenceMode: "NO_DATABASE_LOOKUP_IN_THIS_ROUTE",
    eventKnownByThisRoute: false,
    databaseReadPerformed: false,
    eventCreated: false,
    opcCreated: false,
    auditCreated: false,
    usageCreated: false,
    requestedEventId: query.eventId,
    requestedLimit: query.limit,
    returnedEvents: [],
    returnedCount: 0,
    requestHash,
    note:
      "Runtime EVT records remain owned by the internal EVT ledger. This v1 public endpoint defines the external contract and safe lookup envelope. Database-backed lookup can be wired later without changing the public shape."
  };
}

function buildSampleEvent(query: EventQuery, generatedAt: string) {
  const eventSeed = JSON.stringify({
    eventType: "GOVERNED_CHAT_RESPONSE",
    subjectIpr: query.humanIpr,
    runtimeIpr: query.runtimeIpr,
    tenant: query.tenant,
    workspace: query.workspace,
    createdAt: generatedAt,
    legalCertification: LEGAL_CERTIFICATION,
    opcBoundary: OPC_BOUNDARY
  });

  return {
    eventId: "EVT-V1-SAMPLE-GOVERNED-CHAT-RESPONSE",
    eventType: "GOVERNED_CHAT_RESPONSE",
    subjectIpr: query.humanIpr,
    runtimeIpr: query.runtimeIpr,
    tenant: query.tenant,
    workspace: query.workspace,
    createdAt: generatedAt,
    eventHash: sha256(eventSeed),
    linkedOpcId: "OPC-V1-SAMPLE-TECHNICAL-PROOF-RECEIPT",
    linkedAuditId: "AUDIT-V1-SAMPLE-RUNTIME-AUDIT-LOG",
    linkedUsageId: "USAGE-V1-SAMPLE-MODEL-USAGE-LOG",
    legalCertification: LEGAL_CERTIFICATION,
    opcBoundary: OPC_BOUNDARY
  };
}

export async function GET(request: NextRequest): Promise<NextResponse> {
  const generatedAt = isoNow();
  const query = normalizeEventQuery(request);

  return NextResponse.json(
    {
      status: "HBCE_IPR_RUNTIME_EVENTS_CONTRACT_READY",
      revision: ROUTE_REVISION,
      generatedAt,
      product: PRODUCT_NAME,
      apiVersion: API_VERSION,
      runtime: RUNTIME_NAME,
      identity: {
        humanIpr: query.humanIpr,
        runtimeIpr: query.runtimeIpr,
        tenant: query.tenant,
        workspace: query.workspace,
        access: "ACCESS_GRANTED",
        identityBinding: "IPR_OPERATIONAL_IDENTITY_BOUND"
      },
      eventLedger: buildEventContract(),
      lookup: buildLookupEnvelope(query, generatedAt),
      sampleEventShape: buildSampleEvent(query, generatedAt),
      temporalSeal: buildTemporalSeal(generatedAt),
      publicSurface: buildPublicSurface(),
      boundary: buildBoundary()
    },
    {
      status: 200,
      headers: {
        "Cache-Control": "no-store",
        "X-HBCE-API-Version": API_VERSION,
        "X-HBCE-Route-Revision": ROUTE_REVISION,
        "X-HBCE-Legal-Certification": "false",
        "X-HBCE-OPC-Boundary": OPC_BOUNDARY
      }
    }
  );
}
