import { createHash } from "node:crypto";

import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const revalidate = 0;

const ROUTE_REVISION =
  "HBCE-IPR-RUNTIME-API-v1-MODEL_USAGE_LOOKUP_CONTRACT-v1.0";

const API_VERSION = "v1";
const PRODUCT_NAME =
  "HBCE IPR Operational Identity & Proof Layer";
const RUNTIME_NAME =
  "AI_JOKER_C2_SAAS_CORE_v0_1";

const DEFAULT_HUMAN_IPR =
  "IPR-88505FE91013DCFE97C56ED1";
const DEFAULT_RUNTIME_IPR =
  "IPR-AI-0001";
const DEFAULT_TENANT =
  "HBCE-TENANT-SELF-PILOT";
const DEFAULT_WORKSPACE =
  "HBCE-WORKSPACE-RND";

const LEGAL_CERTIFICATION = false;

const MODEL_USAGE_BOUNDARY =
  "Model Usage records are technical-operational telemetry records. They do not constitute billing certification, legal certification, model ownership evidence or provider attestation.";

const OPC_BOUNDARY =
  "technical proof receipt only";

type RouteContext = {
  params: Promise<{
    usageId: string;
  }>;
};

type ModelUsageQuery = {
  usageId: string;
  humanIpr: string;
  runtimeIpr: string;
  tenant: string;
  workspace: string;
};

type ModelUsageContractReceipt = {
  usageId: string;
  provider: string;
  providerState: string;
  model: string;
  modelLevel: string;
  inputTokens: number | null;
  outputTokens: number | null;
  totalTokens: number | null;
  evtId: string | null;
  auditId: string | null;
  threadId: string | null;
  createdAt: string;
  usageHash: string;
  legalCertification: false;
};

function isoNow(): string {
  return new Date().toISOString();
}

function sha256(value: string): string {
  return `sha256:${createHash("sha256")
    .update(value, "utf8")
    .digest("hex")}`;
}

function safeString(value: string | null): string | null {
  if (typeof value !== "string") {
    return null;
  }

  const trimmed = value.trim();

  return trimmed.length > 0
    ? trimmed
    : null;
}

function normalizeUsageId(value: string): string {
  const normalized = value.trim();

  if (!normalized) {
    return "USAGE-ID-NOT-PROVIDED";
  }

  return normalized.slice(0, 256);
}

function normalizeQuery(
  request: NextRequest,
  usageId: string,
): ModelUsageQuery {
  const searchParams =
    request.nextUrl.searchParams;

  return {
    usageId:
      normalizeUsageId(usageId),

    humanIpr:
      safeString(
        searchParams.get("humanIpr"),
      ) ?? DEFAULT_HUMAN_IPR,

    runtimeIpr:
      safeString(
        searchParams.get("runtimeIpr"),
      ) ?? DEFAULT_RUNTIME_IPR,

    tenant:
      safeString(
        searchParams.get("tenant"),
      ) ?? DEFAULT_TENANT,

    workspace:
      safeString(
        searchParams.get("workspace"),
      ) ?? DEFAULT_WORKSPACE,
  };
}

function buildIdentity(
  query: ModelUsageQuery,
) {
  return {
    humanIpr:
      query.humanIpr,

    runtimeIpr:
      query.runtimeIpr,

    tenant:
      query.tenant,

    workspace:
      query.workspace,

    access:
      "ACCESS_GRANTED",

    identityBinding:
      "IPR_OPERATIONAL_IDENTITY_BOUND",

    authority:
      "SERVER_RUNTIME_VALIDATED",
  };
}

function buildModelUsageContract() {
  return {
    status:
      "MODEL_USAGE_CONTRACT_READY",

    ledger:
      "MODEL_USAGE",

    purpose:
      "Model Usage records technical information about a governed AI execution, including provider, model, execution state, token telemetry when available, linked EVT and linked audit references.",

    usageIdFormat:
      "USAGE-<YYYYMMDDHHMMSS>-<8_HEX> or USAGE-V1-<DOMAIN>-<HASH>",

    minimumFields: {
      usageId:
        "string",

      provider:
        "string",

      providerState:
        "string",

      model:
        "string",

      modelLevel:
        "string",

      inputTokens:
        "number | null",

      outputTokens:
        "number | null",

      totalTokens:
        "number | null",

      createdAt:
        "ISO-8601 UTC timestamp",

      usageHash:
        "sha256:<hex>",

      legalCertification:
        false,
    },

    optionalRelations: {
      evtId:
        "May reference the EVT generated by the same governed execution.",

      auditId:
        "May reference the audit record generated by the same governed execution.",

      threadId:
        "May reference the governed conversation thread.",

      tenant:
        "May identify the SaaS tenant boundary.",

      workspace:
        "May identify the SaaS workspace boundary.",
    },

    tokenSemantics: {
      unavailable:
        "Token values may be null when the provider does not return usage telemetry.",

      zero:
        "Zero is a valid explicit token count and is distinct from telemetry not being available.",

      total:
        "When available, totalTokens should equal inputTokens plus outputTokens.",
    },
  };
}

function buildLookupEnvelope(
  query: ModelUsageQuery,
  generatedAt: string,
) {
  const requestHash =
    sha256(
      JSON.stringify({
        endpoint:
          "GET /api/v1/model-usage/[usageId]",

        usageId:
          query.usageId,

        humanIpr:
          query.humanIpr,

        runtimeIpr:
          query.runtimeIpr,

        tenant:
          query.tenant,

        workspace:
          query.workspace,

        generatedAt,
      }),
    );

  return {
    status:
      "MODEL_USAGE_LOOKUP_NOT_PERSISTED_BY_THIS_ROUTE",

    lookupMode:
      "CONTRACT_RECEIPT_ONLY",

    persistenceMode:
      "NO_DATABASE_LOOKUP_IN_THIS_ROUTE",

    requestedUsageId:
      query.usageId,

    usageKnownByThisRoute:
      false,

    databaseReadPerformed:
      false,

    databaseWritePerformed:
      false,

    modelCallPerformed:
      false,

    evtCreated:
      false,

    opcCreated:
      false,

    auditCreated:
      false,

    memoryCreated:
      false,

    requestHash,

    record:
      null,

    note:
      "The internal model_usage ledger owns persisted usage records. This public route currently exposes the stable external contract and safe lookup envelope only.",
  };
}

function buildSampleRecord(
  query: ModelUsageQuery,
  generatedAt: string,
): ModelUsageContractReceipt {
  const sample = {
    usageId:
      "USAGE-V1-SAMPLE-GOVERNED-MODEL-EXECUTION",

    provider:
      "OPENAI",

    providerState:
      "COMPLETED",

    model:
      "gpt-5.5",

    modelLevel:
      "STANDARD",

    inputTokens:
      128,

    outputTokens:
      64,

    totalTokens:
      192,

    evtId:
      "EVT-V1-SAMPLE-GOVERNED-MODEL-EXECUTION",

    auditId:
      "AUDIT-V1-SAMPLE-GOVERNED-MODEL-EXECUTION",

    threadId:
      "THREAD-V1-SAMPLE-GOVERNED-MODEL-EXECUTION",

    createdAt:
      generatedAt,

    legalCertification:
      false as const,
  };

  return {
    ...sample,

    usageHash:
      sha256(
        JSON.stringify({
          ...sample,
          humanIpr:
            query.humanIpr,
          runtimeIpr:
            query.runtimeIpr,
          tenant:
            query.tenant,
          workspace:
            query.workspace,
        }),
      ),
  };
}

function buildPublicSurface() {
  return {
    currentEndpoint:
      "GET /api/v1/model-usage/{usageId}",

    publicEquivalent:
      "GET /v1/model-usage/{usageId}",

    relatedEndpoints: [
      "GET /v1/health",
      "GET /v1/capabilities",
      "POST /v1/ipr/session",
      "POST /v1/chat",
      "POST /v1/operations",
      "GET /v1/operations/{operationId}",
      "GET /v1/events",
      "GET /v1/opc/{opcId}",
      "GET /v1/audit/{auditId}",
      "GET /v1/model-usage/{usageId}",
    ],

    pathParameters: {
      usageId:
        "Required Model Usage identifier.",
    },

    queryParameters: {
      humanIpr:
        "Optional operational subject IPR.",

      runtimeIpr:
        "Optional runtime IPR.",

      tenant:
        "Optional SaaS tenant identifier.",

      workspace:
        "Optional SaaS workspace identifier.",
    },
  };
}

function buildTemporalSeal(
  generatedAt: string,
) {
  return {
    status:
      "DUAL_TIME_SEAL_READY",

    generatedAtUtc:
      generatedAt,

    locality:
      "Torino / Italia / Europa",

    runtimeBirth:
      "2026-01-19T15:30:00+01:00",

    timezone:
      "Europe/Rome",

    qualifiedTimestamp:
      false,

    legalCertification:
      false,
  };
}

function buildBoundary() {
  return {
    legalCertification:
      LEGAL_CERTIFICATION,

    modelUsageBoundary:
      MODEL_USAGE_BOUNDARY,

    opcBoundary:
      OPC_BOUNDARY,

    readOnly:
      true,

    contractOnly:
      true,

    databaseReadPerformed:
      false,

    databaseWritePerformed:
      false,

    performsModelCall:
      false,

    exposesProviderSecret:
      false,

    exposesRawPrompt:
      false,

    exposesRawOutput:
      false,

    exposesApiKey:
      false,

    createsEvt:
      false,

    createsOpc:
      false,

    createsAudit:
      false,

    createsMemory:
      false,

    replacesProviderBilling:
      false,

    replacesHumanReview:
      false,
  };
}

export async function GET(
  request: NextRequest,
  context: RouteContext,
): Promise<NextResponse> {
  const generatedAt =
    isoNow();

  const params =
    await context.params;

  const query =
    normalizeQuery(
      request,
      params.usageId,
    );

  return NextResponse.json(
    {
      ok:
        true,

      status:
        "HBCE_IPR_RUNTIME_MODEL_USAGE_CONTRACT_READY",

      revision:
        ROUTE_REVISION,

      generatedAt,

      product:
        PRODUCT_NAME,

      apiVersion:
        API_VERSION,

      runtime:
        RUNTIME_NAME,

      identity:
        buildIdentity(query),

      modelUsage:
        buildModelUsageContract(),

      lookup:
        buildLookupEnvelope(
          query,
          generatedAt,
        ),

      sampleRecordShape:
        buildSampleRecord(
          query,
          generatedAt,
        ),

      temporalSeal:
        buildTemporalSeal(
          generatedAt,
        ),

      publicSurface:
        buildPublicSurface(),

      boundary:
        buildBoundary(),
    },
    {
      status:
        200,

      headers: {
        "Cache-Control":
          "no-store, no-cache, must-revalidate, proxy-revalidate",

        Pragma:
          "no-cache",

        Expires:
          "0",

        "X-HBCE-API-Version":
          API_VERSION,

        "X-HBCE-Route-Revision":
          ROUTE_REVISION,

        "X-HBCE-Legal-Certification":
          "false",

        "X-HBCE-Model-Usage-Mode":
          "CONTRACT_RECEIPT_ONLY",
      },
    },
  );
}
